import Head from "next/head";
import Name, { type ColoredNameProps } from '../components/Name'
import Bill from "~/components/Bill";
import { useState } from "react"

export default function Home() {
  const [isConfirm, setIsConfirm] = useState<boolean>(false)
  const [names, setNames] = useState<ColoredNameProps[]>([])

  const handleIsConfirm = () => {
    if (!isConfirm && names.length > 1) {
      setIsConfirm(true)
    }
  }
  return (
    <>
      <Head>
        <title>Bill Spiltter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-flow-row auto-rows-max gap-2">
          <h1 className="text-5xl font-extrabold tracking-tight text-black">
            Bill Spiltter
          </h1>
          <Name {...{isConfirm, names, setNames}} />
          {!isConfirm && <div>
            <button onClick={handleIsConfirm} className="bg-green-500 text-white w-[100px] h-[35px] rounded items-center" disabled={isConfirm || names.length < 2}> Confirm </button>  
          </div>}
          <Bill {...{names}}/>
      </main>
    </>
  );
}
