import Head from "next/head";
import Name, { type ColoredNameProps } from '../components/Name'
import Bill, { type TableProps } from "~/components/Bill";
import { useState } from "react"
import Summary from "~/components/Summary";

export default function Home() {
  const [isConfirm, setIsConfirm] = useState<boolean>(false)
  const [names, setNames] = useState<ColoredNameProps[]>([])
  const [table, setTable] = useState<Array<TableProps>>([])

  const handleIsConfirm = () => {
    if (!isConfirm && names.length > 1) {
      setIsConfirm(true)
    }
  }
  return (
    <>
      <Head>
        <title>Bill Spiltter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-flow-row auto-rows-max gap-2 flex items-center justify-center h-screen">
          <h1 className="text-5xl font-extrabold tracking-tight text-black">
            Bill Spiltter
          </h1>
          <Name {...{isConfirm, names, setNames}} />
          <Bill {...{names, table, setTable}}/>
          <Summary {...{names, table}} />
      </main>
    </>
  );
}
